# Generated by Django 6.0.6 on 2026-07-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
