# Generated by Django 6.0.6 on 2026-07-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_refundrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='delivery',
        ),
    ]
